image:
  repository: us-docker.pkg.dev/myproj/repo/service-a
  tag: "latest"
replicaCount: 2
resources:
  requests: { cpu: "200m", memory: "256Mi" }
  limits:   { cpu: "500m", memory: "512Mi" }
ingress:
  enabled: true
  className: nginx
  hosts: [service-a.stage.example.com]
