name: CI
on:
  pull_request:
    branches: [ main, develop ]
    paths: ['apps/*','.github/*']
  push:
    branches: [ main, 'release/*']
permissions:
  id-token: write # for OIDC
  contents: read
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: pip-audit -r app/service_a/requirements.txt || true
      - run: pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=xml || true
      - name: Lint & Typecheck
        run: |
            black --check apps/
            mypy apps/ 
      - name: Unit tests
        run: |
            pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=xml
      - name: Dependency audit
        run: pip-audit -r app/service_a/requirements.txt || true
      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2 || true
env:
  ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
  run: |
      IMAGE_TAG=${GITHUB_SHA::7}
      docker build -t $ECR_REGISTRY/service-a:$IMAGE_TAG -f app/service_a/Dockerfile .
      echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Push image
      docker push $ECR_REGISTRY/service-a:${IMAGE_TAG}

